### PR TITLE
Stop mixing prs across branches

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Currently having trouble with pipelines so can't merge right now. http://jenkins.jx.35.240.9.95.nip.io/job/Activiti/job/activiti-build/job/7.0.x/12/console resulted in https://github.com/Activiti/Activiti/pull/2556/files , which is a mixture of the 7.0.x and 7.1.x release trains - more specifically the 7.0.x train made a commit to overwrite a PR on the 7.1.x train

That PR is https://api.github.com/repos/Activiti/Activiti/pulls/2556 - from there we can see that the base branch has a ref (`develop`) and updatebot needs to check the base branch ref [against its yaml file for that repo](https://github.com/Activiti/activiti-build/blob/develop/.updatebot.yml) before performing the update

Also happens to include changes for https://github.com/jenkins-x/updatebot/pull/69 as based on same fork

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
Will be testing this with https://github.com/ryandawsonuk/updatebottestforbranches

**Comment by ryandawsonuk** [comment]
Have now used that tester project to successfully do the following:

1) Create a new PR to 7.0.x branch when no existing PR https://github.com/Activiti/activiti-api/pull/94/files
2) Create new PR to 7.0.x branch https://github.com/Activiti/Activiti/pull/2557 without changing existing PR to develop branch on same repo i.e. it did not update https://github.com/Activiti/Activiti/pull/2556 which was open at the same time
3) Update an existing PR to 7.0.x branch https://github.com/Activiti/activiti-dependencies/pull/125/files

**Comment by igdianov** [comment]
@ryandawsonuk I added fix to include base branch ref to PR title in order to distinguish between single PRs  using different base branch configurations.

**Comment by igdianov** [comment]
Here is the screenshot of two single PRs in https://github.com/Activiti/Activiti/pulls for each branch:

## develop branch:

image

## 7.0.x branch:

image

**Pull request merged**
