### PR TITLE
feat: use single pull request for downstream repositories

### PR DESCRIPTION
**Pull request by igdianov**
Currently, any updatebot push-version command will create a separate PR in the downstream repository for each upstream source. This makes it impossible to use with distributed Maven projects that need to propagate their versions through a build graph into a single PR in aggregator pom repository to validate that all common dependency versions for managed pom modules converge before merging valid managed dependencies artifacts into release branch.

This PR introduces optional attribute `useSinglePullRequest` for Github repositories in .updatebot.yml configuration file to add, commit and push version changes into single pull request to downstream repository from multiple upstream repositories, so that, if `useSinglePullRequest` is set to `true` for repository in .updatebot.yml, the updatebot push-version command will

1. Resolve and checkout an existing pull request branch from downstream repository
2. Add version changes commits with comments into local pull request branch
3. Push changes into single pull request remote branch to trigger PR preview job.

I had setup the following repositories in my Jenkins-X cluster to test Updatebot binary built from this PR:

https://github.com/igdianov/foo

```yaml
github:
  organisations:
  - name: igdianov
    repositories:
    - name: bar
    - name: foobar
      useSinglePullRequest: true
``` 

https://github.com/igdianov/bar

```yaml
github:
  organisations:
  - name: igdianov
    repositories:
    - name: foobar
      useSinglePullRequest: true
``` 

https://github.com/igdianov/foobar

```yaml
github:
  organisations:
  - name: igdianov
    repositories:
``` 

The repositories are configured so that any successful commit to Foo master pushes its release version to Bar with normal PR and Foobar with single PR. Any successful commit to Bar master pushes Bar version to Foobar with single PR. Foobar pom.xml is using Maven enforcer plugin to validate dependency convergence between managed modules for each commit pushed into single PR branch.  The PR build fails fast if the current dependencies do not converge.

Once all versions change commits have been propagated and validated for single Foobar PR, the foobar-tests module will run integration tests and let Jenkins report the pr status back to Github. Then the single PR with valid status will be merged into master to build and deploy foobar-dependencies artifact with valid managed dependencies versions bundle downstream.

### CODE REVIEW

**Comment by igdianov** [comment]
@jstrachan Let me know if there is any problem with this PR. Thank you!

**Comment by jstrachan** [comment]
@igdianov many thanks!

**Comment by igdianov** [comment]
@jstrachan Thank you! Could give this one a kick to push updatebot release into builders? https://github.com/jenkins-x/builder-base/pull/651

**Comment by jstrachan** [comment]
will do - we've just been transitioning our production Jenkins X installation over to serverless jenkins + prow - so please bear with us for a day to make sure everything gets sorted; we're making a few changes + switching to a mono repo for all the `builder-*` images to avoid hitting github API limits ;)

**Pull request merged**
